### ISSUE TITLE
Add termination Grounds coding scheme

### ISSUE THREAD

**Issue by jhollway** [globalgov/qEnviron#20]

**Comment by EstherPeev** [comment]
Here is a document listing some of the treaties with an "End" date and their related termination clause from GNEVAR dataset. Most of them have a "sunset/expiry" clause type. The key words to detect the termination clauses are highlighted in bold.  

[https://app.zenhub.com/files/326714201/5c9af4b9-eb4d-4933-8e21-cba8ca2be5d6/download](https://app.zenhub.com/files/326714201/5c9af4b9-eb4d-4933-8e21-cba8ca2be5d6/download)

**Comment by jhollway** [comment]
Great, thanks @EstherPeev . Can you perhaps make a start on a function that would code this, starting from what can be extracted from treaty titles, before we move on to treaty texts?

**Comment by EstherPeev** [comment]
Here is the same document as above with two extra pages in order to have more examples of termination clauses, which could be helpful for the future text analysis:

[https://app.zenhub.com/files/326714201/c730a41c-ab1a-4249-986d-14988b9ccb32/download](https://app.zenhub.com/files/326714201/c730a41c-ab1a-4249-986d-14988b9ccb32/download)

@jhollway For the function, I worked on a first version (see in my last commit on qCreate) that I called `code_term()`, which extracts the term date from the treaty title and also indicates the type of termination (in that case, "Sunset/Expiry"). It is the first version and I can easily adapt it if you think only the type or the term date should appear. Please, let me know what you think is best or what requires changes.

**Comment by jhollway** [comment]
Great start @EstherPeev . Do you think it makes more sense to have two functions, `code_term_type()` and `code_term_date()`, or have these options as an argument to `code_term()` -- or both?

**Comment by EstherPeev** [comment]
I think it would be make more sense to have two separate functions (`code_term_type()` and `code_term_date()`) so that the user can easily chose what he prefers to have as an output and I also think it is more intuitive.

**Comment by jhollway** [comment]
See also [https://app.zenhub.com/files/326714201/435824b0-d0f5-410f-b6a8-76427e902225/download](https://app.zenhub.com/files/326714201/435824b0-d0f5-410f-b6a8-76427e902225/download)
